# Generated by Django 5.0.4 on 2024-04-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0002_rename_user_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="DateofBirth",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("audio", models.FileField(upload_to="audios/")),
                ("Date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Database.account",
                    ),
                ),
            ],
        ),
    ]
