# Generated by Django 5.0.4 on 2024-04-09 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0004_alter_account_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="DateofBirth",
        ),
    ]
