# Generated by Django 5.0.4 on 2024-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0006_account_dateofbirth_alter_account_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="Fname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="account",
            name="Lname",
            field=models.CharField(default="", max_length=100),
        ),
    ]
