# Generated by Django 5.0.4 on 2024-04-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0007_account_fname_account_lname"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_image",
            field=models.ImageField(
                default="profile/default.jpg", upload_to="profile/"
            ),
        ),
    ]
