# Generated by Django 5.0.4 on 2024-04-09 19:02

import Database.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0008_account_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="artist_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="audio",
            name="video",
            field=models.FileField(
                default="",
                upload_to="videos/",
                validators=[Database.models.validate_file_video],
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="audio",
            field=models.FileField(
                upload_to="audios/", validators=[Database.models.validate_file_audio]
            ),
        ),
        migrations.CreateModel(
            name="Enhanced_audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "audio",
                    models.FileField(
                        upload_to="audios/",
                        validators=[Database.models.validate_file_audio],
                    ),
                ),
                ("Date", models.DateTimeField(auto_now_add=True)),
                ("artist_name", models.CharField(default="", max_length=100)),
                (
                    "video",
                    models.FileField(
                        default="",
                        upload_to="videos/",
                        validators=[Database.models.validate_file_video],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Database.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pre_pro_audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "audio",
                    models.FileField(
                        upload_to="audios/",
                        validators=[Database.models.validate_file_audio],
                    ),
                ),
                ("Date", models.DateTimeField(auto_now_add=True)),
                ("artist_name", models.CharField(default="", max_length=100)),
                (
                    "video",
                    models.FileField(
                        default="",
                        upload_to="videos/",
                        validators=[Database.models.validate_file_video],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Database.account",
                    ),
                ),
            ],
        ),
    ]
