# Generated by Django 5.0.4 on 2024-05-09 21:39

import Database.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0010_evaluation_rvc_audio_upscaled_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="video",
            field=models.FileField(
                blank=True,
                default="",
                null=True,
                upload_to="videos/",
                validators=[Database.models.validate_file_video],
            ),
        ),
        migrations.AlterField(
            model_name="enhanced_audio",
            name="video",
            field=models.FileField(
                blank=True,
                default="",
                null=True,
                upload_to="videos/",
                validators=[Database.models.validate_file_video],
            ),
        ),
    ]
