# Generated by Django 5.0.4 on 2024-05-10 01:57

import Database.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0011_alter_audio_video_alter_enhanced_audio_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upscaled_audio",
            name="video",
            field=models.FileField(
                blank=True,
                default="",
                null=True,
                upload_to="videos/",
                validators=[Database.models.validate_file_video],
            ),
        ),
    ]
