# Generated by Django 5.0.4 on 2024-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0012_alter_upscaled_audio_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
