# Generated by Django 5.0.4 on 2024-05-10 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0013_alter_audio_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="user",
        ),
    ]
