# Generated by Django 5.0.4 on 2024-05-10 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0014_remove_audio_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upscaled_audio",
            name="user",
        ),
    ]
