# Generated by Django 5.0.4 on 2024-05-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0016_account_groups_account_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
