# Generated by Django 5.0.4 on 2024-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0019_rename_user_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
