# Generated by Django 5.0.4 on 2024-06-27 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0020_account_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enhanced_audio",
            name="user",
        ),
    ]
