# Generated by Django 5.0.4 on 2024-04-05 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('Artist_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Artist_Name', models.CharField(max_length=100)),
                ('Artist_voice', models.FileField(upload_to='uploads/')),
                ('Artist_image', models.FileField(upload_to='uploads/')),
                ('Artist_songs', models.FileField(upload_to='uploads/')),
                ('song_lyrics', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_number', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Postal_Code', models.IntegerField(blank=True, null=True)),
                ('user_image', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('Sub_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Card_No', models.BigIntegerField()),
                ('CVV', models.IntegerField()),
                ('Card_Name', models.CharField(max_length=100, unique=True)),
                ('End_Date', models.CharField(max_length=10)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='pre_pro',
            fields=[
                ('time', models.TimeField(auto_created=True, auto_now=True)),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('Pre_pro_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Pre_pro_Name', models.CharField(max_length=100)),
                ('Pre_pro_audio', models.FileField(upload_to='uploads/')),
                ('size', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enhanced_audio',
            fields=[
                ('time', models.TimeField(auto_created=True, auto_now=True)),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('Enhanced_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Enhanced_Name', models.CharField(max_length=100)),
                ('Enhanced_audio', models.FileField(upload_to='uploads/')),
                ('size', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('time', models.TimeField(auto_created=True, auto_now=True)),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('Audio_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Audio_Name', models.CharField(max_length=100)),
                ('Audio', models.FileField(upload_to='uploads/')),
                ('size', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
