# Generated by Django 5.0.4 on 2024-04-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Artist_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/artist_img/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_songs',
            field=models.FileField(blank=True, null=True, upload_to='uploads/song/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_voice',
            field=models.FileField(blank=True, null=True, upload_to='uploads/voice/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='song_lyrics',
            field=models.FileField(blank=True, null=True, upload_to='uploads/lyrics/'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='Audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/up_audio/'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='Audio_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audio',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enhanced_audio',
            name='Enhanced_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enhanced_audio',
            name='Enhanced_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Enhanced_Audio/'),
        ),
        migrations.AlterField(
            model_name='enhanced_audio',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_pro',
            name='Pre_pro_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pre_pro',
            name='Pre_pro_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pre_pro',
            name='Pre_pro_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pre_audio/'),
        ),
        migrations.AlterField(
            model_name='pre_pro',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Sub_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/profile_img/'),
        ),
    ]
