# Generated by Django 5.0.4 on 2024-04-07 21:20

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_artist_artist_id_alter_artist_artist_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="Artist_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/artist_img/"
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="Artist_songs",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/song/",
                validators=[myapp.models.validate_audio_file],
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="Artist_voice",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/voice/",
                validators=[myapp.models.validate_audio_file],
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="song_lyrics",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/lyrics/",
                validators=[myapp.models.validate_text_file],
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="Audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/up_audio/",
                validators=[myapp.models.validate_audio_file],
            ),
        ),
        migrations.AlterField(
            model_name="enhanced_audio",
            name="Enhanced_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/Enhanced_Audio/",
                validators=[myapp.models.validate_audio_file],
            ),
        ),
        migrations.AlterField(
            model_name="pre_pro",
            name="Pre_pro_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/pre_audio/",
                validators=[myapp.models.validate_audio_file],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profile_img/"
            ),
        ),
    ]
